config/routes.rb
# frozen_string_literal: true

# returns true if the agent is a bot
class BotsConstraint
  def matches?(request)
    /bot/ =~ request.headers['User-Agent']
  end
end

# returns true if the agent is not a bot
class HumansConstraint
  def matches?(request)
    /bot/ !~ request.headers['User-Agent']
  end
end

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  scope constraints: BotsConstraint.new do
    get '/installers/:path', to: 'installers#download'
  end

  scope constraints: HumansConstraint.new do
    get '/installers', to: 'installers#show'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/installer.rb
class Installer < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/installers_controller.rb
# frozen_string_literal: true

# Controller for /installer and /installer/:path
# returns a lua installer for a turtle (etc.) or a xml-schema
class InstallersController < ApplicationController
  # returns a lua file containing the installer
  def download
    @installer = Installer.find(params[:path])
  end

  # returns a xml file representing the data from the installer model
  def show

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/installers_helper.rb
module InstallersHelper
end

app/views/installers/show.html.erb
<%= link_to 'Patient Record', installer_path(@installer) %>
<h1>Installers#show</h1>
<p>Find me in app/views/installers/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ccserver</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>